---
# S3 credentials for Mimir long-term storage
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: s3-credentials
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hcloud-default-s3/username
        metadataPolicy: None
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hcloud-default-s3/password
        metadataPolicy: None
      secretKey: AWS_SECRET_ACCESS_KEY
