---
# Strimzi Kafka cluster for Mimir ingest storage (KRaft mode - no ZooKeeper)
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mimir-kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV0
    # Enable Prometheus JMX metrics
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9404"
            prometheus.io/path: "/metrics"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # Retention for ingest storage - keep data long enough for ingesters to consume
      # Reduced from 24h to 6h since ingesters flush to S3 much faster
      log.retention.hours: 6
      log.retention.bytes: -1
      # Segment settings for faster cleanup
      log.segment.bytes: 134217728
      log.cleanup.policy: delete
      # Message size limits for Mimir ingest storage
      # Mimir's producer_max_record_size_bytes defaults to ~15.24 MB
      # Must be >= Mimir's limit to avoid MESSAGE_TOO_LARGE errors
      message.max.bytes: 16777216
      replica.fetch.max.bytes: 16777216
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
    userOperator:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
---
# KafkaNodePool with combined controller and broker roles (KRaft mode)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: combined
  labels:
    strimzi.io/cluster: mimir-kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
        kraftMetadata: shared
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 2Gi
---
# Kafka topic for Mimir ingest storage
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mimir-ingest
  labels:
    strimzi.io/cluster: mimir-kafka
spec:
  partitions: 12
  replicas: 3
  config:
    retention.ms: 21600000  # 6 hours (matches broker log.retention.hours)
    min.insync.replicas: 2
    max.message.bytes: 16777216  # 16 MB (matches broker message.max.bytes)
