goldilocks:
  controller:
    enabled: true
    revisionHistoryLimit: 0
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M

  dashboard:
    enabled: true
    revisionHistoryLimit: 0
    replicaCount: 1
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
