---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    password: AgAlcAYwGL6e+xfF/BCvfMwliFps+XR2pcdzR2XnzYYwrQaYxBOOLE20PD/CbPuZjrmO4/RC3JUmcSO86lr2V/cu1ctCIbE05NS1F9dMaVBFmY73/fhW3+ji3FYiD9HTUByt9mCsKoat7UaBqkZCAWczZAOwevyY8DqTh8huq2oQXdrTSDUUoL3ykNhja465fN9cDZfjkh+pjgMEJVA3PjC6L+oTOjq6fiPdhYwJYlF4ORAtWXZq37Yh/l7JG6/JeZiQY4cSxUe8g6cRoQlKbHIAy22L/V/y840qhBBzh+rWJhnND9El+CAivqvtx3bsoZrzlzO6fMm4pTQm9ZIi+MYM1Aq3c0KhiDvOWYG/10p8pkoDlsjT8+LmFesWAJUytIfzhspcxTfgMW+nMaItNdlkKQvk/zFv86VrVVbAbgBEOAezV7+JjCwZcC90eIsCqaHzVjIRATv6V2cKSpMHO+6GGPk4/sz1Pv8rSJ0tRhTrTEbF5rrQrT8EsKQrk/wZ+IV5vH8GikYHEfmrGGtHGywwixlmdyXrJTsmDS+yL79RaVIB7Fe1SuHpIq9bkCor6zJxFD46PD/zHamb1m8yivzCHJD6o9KWhPdXwdWlci4nH77Wh8sZDsbW8n6BhJLXcQ5qEzm4f6f+RU4Rq4iUCvOzVmLXs/11I3xdFzlacfcLwn1LQb+cmXKTWL9AhvtN88ZJsIY3ZXzSqQstotJ9l03o
    user: AgCUr1k8QXAbL42zDWskQ2m7xtZMQOBu+YBWRarBWz+p+/lvlOsc0uxeCDGFBP0Ey1unT/OcoB0xu4MJe1cTYqw8ZsfzLreIv3sX/0+2eA7iDKFgxuuKUCGFbw8Y9/eRvLEMsiecpSeoTniON7QF2I/d+ZFPRHJP41CymHVvK2RFEukYXhJqntrZeHbsYHEj0C52CmbjtVUGNo6xhRhQhmQvFKoZPsQOiAnwr7//9tVZ1PgH5oIivQ7o1N5m0TCKnax/HOlqdp9wxFNLpB1qhC9/azgtOSKKJMCQUAypDfhoWqywSitBArdzE4/8+oM2X6DCiO73UNCxMa1d3RUIROue2xwi/m+1NRmSlv98cuQdB7CIzgbrSomlDy3qSyzUyoJxpaKVGdJCeoJHTrwSaMM1VtUASNivgYXWqVBxkhldzN8p/iw3lbCUA+x79BUkekjta6lD4bBsl0wgjt2sgWgW3dyopfq7Tq01uRleOmj+7X3bki/AtIn8qIH5HOwAKtJ6KVLLop2lM8nAKWBZXIjNwJ0vT/sCaOBpOzt2ihXij+gwTyf3zcKFSRzF/4Zr6B9b2wYAEu/pVfDlX7ZG01bMZRvKXcvLcGWQ94iX81DvBKTvyoQJo0clfCePDaRDME6K5PHVQWeAd2Ix4Kl3022qixEsBC3f3nTQbm9RcVgtUezQwe2w+cf/RLAg9M22uEBKMf7fBA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: kube-prometheus-stack
