cert-manager:
  crds:
    enabled: true
    keep: true

  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 64Mi

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

  webhook:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi
    timeoutSeconds: 20

  cainjector:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi

  startupapicheck:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi
