tailscale-operator:
  ingressClass:
    enabled: true

  installCRDs: true

  operatorConfig:
    defaultTags:
      - tag:k8s-operator
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        memory: 100Mi
