apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: picosense-timescaledb
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: timescaledb
    major: 16
  postgresUID: 1000
  postgresGID: 1000
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
  postgresql:
    shared_preload_libraries:
      - timescaledb