apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: picosense-timescaledb
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: timescaledb
    major: 16
  storage:
    size: 10Gi