vpa:
  recommender:
    enabled: true

    replicaCount: 2

    revisionHistoryLimit: 0

    podDisruptionBudget:
      minAvailable: 1

    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M

    podMonitor:
      enabled: false
      annotations: {}
      labels: {}

  updater:
    enabled: true

    replicaCount: 2

    revisionHistoryLimit: 0

    podDisruptionBudget:
      minAvailable: 1

    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M

    podMonitor:
      enabled: false
      annotations: {}
      labels: {}

  admissionController:
    enabled: true

    replicaCount: 2

    revisionHistoryLimit: 0

    podDisruptionBudget:
      minAvailable: 1

    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
