apiVersion: v2
name: istio
description: A Helm chart for Istio service mesh
type: application
version: 0.1.0

dependencies:
  - name: base
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
  - name: cni
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
  - name: ztunnel
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
