---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: AgDKLdV6Jmz6Yx53U4qLYKYUDJEv/fWuQ4vMd1PSdwlWLE+TVNIbav6gsdbo5fLmOjj1VIHCJ/C7sovpAjIdMu6s0k20a3Fv0LLDhkWd8nHNu4iJHkujEAacBKXiUhZMYfiCsES+klF9IxeQPaY+cfzhokp977w0FiCaAJKd0/buxSFJP5hVGQslo5UJFN9B7WHzMp9EavukbT2muSBEY4nF8aMPPRaca4FZAmiga1rxhnx1mvp/hlKEzUkkC65EsYwAukyJXIPwJu6ZW8fUT/EhcC+itSknjKKxOnDKOblZNQgTWDntzSVpiV2TlxNxzqLw87YObdZZkMlwO3vRqNQGQ7BuGyfAGmmpvel0B0cQUOxBm2WOU5goiNsufI+Q6KrKzP0YFW96dUHJjEG2CXfhrwxUaaq1+cKKFvciKkA/9WQzw6JE/o+mWao7tOwloREX2YIW3RrozIq+4l75tSasRHFpGPabSaoPGDtoQvondb48g4KkVvIM/g3379MuDwsKWztC+l/drvWMrLxVEJNUqQzohL71U56ppkPYEoOAQg/Q4RCfGYQyk8MVRrvvbrY6Fdj/zXbZZAi4wlPGG1bR6npXAGJvpgg5PiXG25MtR2aHDwWZfeitSzGg/7BjuAjvbCua0VGz+zS5fvUu/dDeQh8IRJNlQR9JUWsUM7i/KeI8XcOTwq3beCN9EvJv9qa8ERi4ZGNKZq5X3FTjgFDi
    user: AgAbrSRyTCoZat2GTzdVtWTJOMZCtojNH5AjM4vj7MKcS4FE/L/FHpbbbhno3hnsQd4/fbam0E4MUII+TxkxQDpLt2jqbI33sHCkkrIH6+ymSTSt34lKjtMVCgT+furALLhmxyqTrQEtSgQ7wyLnpDaKk/RUunjFNUobQXgBx5MQnjMYdBK6hhQembjrFqVw9XSYpl0fMlqc8zQU6z+Gk+qYFsqvJBov04M26rjd6drYKUd+sHOvEr1wJv7UOKD0ogtFl5AqMlboyQ/Oa16u1S34JYH4LrpPwGUen7hHjTyyloAbBkvXk8IBlWZ+IsRlCUpOdu9dm1zh2QVYSk7G/ybRTK1JKJF/6/fwLz0fxcG8/R3k86F9C1k7pWQwbLvtEbnj8XGmtkqMotrCTpTZIdQB+1LLe7W/Y7mosszR6cCx45Yk+RS9A6p2n94sdij/bJ8gMekcxksKKQZ3O5LneO89SMoLfqZXi+3LyT/qvk1fkQdGzVZBZlt7BfaYlzmfmioXPt7fO1fEL1WeWiqiIIdPN1gkhkNSZfCvGNN/T3/Nt6zfrdhDSLLwjcfa8z3rxixXmIAvoJaWx1g4a6jyyjFig1TvLjaC/bPjO2Wv66pyWSlHlaDaptUYqvq/q+3lBwcgWvEcJsBSAK9fr2p+cP7FClCfQiJvy5ml2w3Aez5mdkPXdQMz4SO15vfMrWBqYuIHVjFEJA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
