---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    password: AgAhMx1M3bEkxg28tBp7qaELDPvr9UqikuonFct33Sg8xwFssOWxdNm7l6PoNaCThDBOBwyhdGRtCS+YrLzMjwbxZVIQL92jeIUpr/WQ4Ag8nagXQ+7aoOHFeJo+BKVQG+drPkTh10TicYtCrpprMG5hZXITWrGjfLMfyvWEWrcNI4kECwZQM0pfRYeuKzbG/IjgyhkAEOhlf7z1sv/1/bhaF8JrNDxGJvPzsLMhk0IS26fPrEZ0D7t46LvuIv3VEhPqbXI0piNoWjmmtOCzpa+43N45XzuHNrECw4RVpgd574M5pskxJO8N9v9ewkMeZOzbx5b4hJQC1Xg95hBbknKTgtgCvZEt51eSXXQvESr+mgCFNJrThT/fHy5X5U46M8jJk8PyajUDCSqRzjJqRePhUgO3VZcHG6OPGuSQ1DPM6cmspXBfM5RbVNLhG1rfrUhS4gyqeOVigRfaQ+HfyudTbXQcszscUxVxyv4gLN5qkRiCsaevOWW6wa5OY3r9Zx/dn6MFo7oivKQCztp9T3CLF4Z7VeH7Ffa1Qrl24I2JtFih/cMTTv9cxJZktv1SXjlsb/tZmczr7xsbUnsgwHEq/EDvv3OFMcqTbKm2DhQ9YxxaU7KI9BaNjSNvZIWqDsOeAzTPsnZMei5lqX0dSan0DJa3UihbwVq56QECn0pE3TRX4HXwljVkyW1e1OHlnGkK5zz8ESegZZ/16JL0OfMF
    user: AgCM198qL1AWn7VYnqOnX8QsNwBvImk+tzjjfKtK+KnohtCmtxd42hSYePPNg/D3bWSikXIsA4w+msYtVNPZHRKnDVUjdFC1HRwV4yXRMup3VGy5qO8oOAAFP0RvP6hGHGNsnPy4rfivOBERU7ttNXlSfhOCEEg/1yTFFKjwswDIxO1jgzOV+YelA9DAIijkJRnkGMLNpXJDVppt5Ci5YMYwd8YJLnXdyy+vKQhexXMj7nvWJe5Z5YCSaYEwdh7lnQu1c0or3mgWNrJ+SQ1J30IY8nMO5wYv2B8wiC811HtipEZW/eiOP0ufN/7KXO0gNVsO8DXukxVL45gVHzi91uPCUA/OXPezi2G0slEwTbae//iEsOxYukTXP4Z0/5FNbHeHf/PnbSfN7RFs/cl3lQI7dkHrwVdA2v4NeCZoNF7kNpy6CpyrrpXwjGzn9sGohuyPjaFv3779uDsqzHRMIcfzADwP1FpANY7+k3ZjAey7NPpjpIcC2BNgHloysCulDacbRBSazUn6Iin2HQfa40eFGTMvPOfNmXKkQ+xf9nzRKOBz0OHWpXHGwKhkTRhM2RbSNNBoTJ9qDPPANa5dw2+pQ+rqhaTtoG3eWAOO8b/fvRQsj1VvNtZMRfqw+wcgVFEvVE0q7qoKkb4aeZOwYSJd4SfWpZg9lmR51BwlBnR1CQKJz2pv1znv5huXTLzudUE4B9BDrA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: kube-prometheus-stack
