---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: miniflux-admin/username
        metadataPolicy: None
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: miniflux-admin/password
        metadataPolicy: None
      secretKey: password
