---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-postgres
spec:
  instances: {{ .Values.postgresql.instances }}

  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux

  storage:
    size: {{ .Values.postgresql.storage.size }}

  resources:
    requests:
      cpu: {{ .Values.postgresql.resources.requests.cpu }}
      memory: {{ .Values.postgresql.resources.requests.memory }}
    limits:
      memory: {{ .Values.postgresql.resources.limits.memory }}
