apiVersion: v2
type: application
name: cloudnative-pg
description: A Helm chart that deploys the Cloud Native PostgreSQL Operator
version: 0.1.0

dependencies:
  - name: cloudnative-pg
    version: ~0.23
    repository: https://cloudnative-pg.github.io/charts
