# Authorization policy for Loki gateway
# Only allows specific services to access Loki
# NOTE: In ambient mode without a waypoint proxy, only L4 policies are enforced.
# HTTP-level filtering (methods, paths) requires a waypoint proxy.
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: loki-gateway
  namespace: loki
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
  action: ALLOW
  rules:
    # Allow logging-agent to push logs (uses hostNetwork, so matches by node IPs)
    - from:
        - source:
            remoteIpBlocks: ["10.0.0.0/24"]
    # Allow Grafana to query logs
    - from:
        - source:
            namespaces: ["grafana"]
    # Allow loki-canary for health checks
    - from:
        - source:
            namespaces: ["loki"]
---
# Allow internal Loki components to communicate with each other
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: loki-internal
  namespace: loki
spec:
  action: ALLOW
  rules:
    # Allow all traffic from within the loki namespace
    - from:
        - source:
            namespaces: ["loki"]
