# Authorization policy for Grafana
# Allows traffic from Tailscale ingress and n8n
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  action: ALLOW
  rules:
    # Allow traffic from Tailscale operator (ingress proxies)
    - from:
        - source:
            namespaces: ["tailscale-operator"]
    # Allow traffic from n8n (for dashboard embeds, API calls, etc.)
    - from:
        - source:
            namespaces: ["n8n"]
