# Authorization policy for Mimir gateway
# Allows Grafana to query metrics and remote write sources to push metrics
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: mimir-gateway
  namespace: mimir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
  action: ALLOW
  rules:
    # Allow Grafana to query metrics
    - from:
        - source:
            namespaces: ["grafana"]
    # Allow otel-metrics to push metrics
    - from:
        - source:
            namespaces: ["otel-metrics"]
    # Allow internal Mimir components
    - from:
        - source:
            namespaces: ["mimir"]
---
# Allow internal Mimir components to communicate with each other
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: mimir-internal
  namespace: mimir
spec:
  action: ALLOW
  rules:
    # Allow all traffic from within the mimir namespace
    - from:
        - source:
            namespaces: ["mimir"]
    # Allow Strimzi operator to manage Kafka
    - from:
        - source:
            namespaces: ["strimzi-kafka-operator"]
    # Allow otel-metrics to scrape Prometheus metrics
    - from:
        - source:
            namespaces: ["otel-metrics"]
---
# Allow Kubernetes API server to reach rollout-operator webhook
# API server is outside the mesh and needs to call admission webhooks
# PERMISSIVE allows both mTLS and plain TLS connections
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: rollout-operator-webhook
  namespace: mimir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rollout-operator
  mtls:
    mode: PERMISSIVE
---
# Allow all traffic to rollout-operator (needed for kube-apiserver webhooks)
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: rollout-operator
  namespace: mimir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rollout-operator
  action: ALLOW
  rules:
    - {}
