# Authorization policy for n8n
# Only allows traffic from Tailscale ingress
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: n8n
  namespace: n8n
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  action: ALLOW
  rules:
    # Allow traffic from Tailscale operator (ingress proxies)
    - from:
        - source:
            namespaces: ["tailscale-operator"]
