---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password-kubernetes
spec:
  provider:
    onepasswordSDK:
      vault: Kubernetes
      auth:
        serviceAccountSecretRef:
          name: 1password-kubernetes-token
          key: token