---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default
spec:
  provider:
    onepasswordSDK:
      vault: Kubernetes
      auth:
        serviceAccountSecretRef:
          name: 1password-kubernetes-token
          key: token
          namespace: {{ .Release.Namespace }}
  conditions:
    - namespaces:
        - "grafana"