metrics-server:
  replicas: 2

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      memory: 500Mi
