metrics-server:
  replicas: 2

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    memory: 105M
