---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale-operator
spec:
  encryptedData:
    clientId: AgAftcy+Y9QoQEy0nJIuTZSafO3RG0TW29Wvaoegzo+m3s6+M9lSeVTKw7BmhNJYnQTaoF5KcIM0rulAzhFwDgEKknQ82nJ1+oCefFGKL/pGSrwmojLEeWN+j/NUqfXGWpd/psHl0uqkzqy403NN1+BZgHzKotvszZjs3IqXevnaNaRLSyo5f+AxCDCuc/wtaYH6newfM0OUlNjveRblaQfGk67Ls++KGF2SlKDuDjbWUUe5mXMSo3UMZ6mvWAfF+aHjr8sN+R4Oc3lGfZR6OstxUeKunQ0sFIlUYiVbvjuDa7MOZ/AJwwilTAdDjiE09v4Al4dswDfWavu5V+QZAR/4oR8Jd5Pc4/leo73FMW+vKcg6+EiB+LJbDc+DyGIumZXuMEKn03A5VyzBrbhzYunYRoeuycB7F/xBldpfJOc6yfkYFXu9hJkD2PqUlspYNfj2QxQPRRVtwQGUA2uV3EVYBZlTu1nlfRz9spjMOO8W0n2K37PsRjXyAcXoKuqClGr3jbonMtefrfMbB9LtJJm7DCOTtnJ8ORjNOtDgXY159Y/fcghTbKKRN9xGeGR+WXVnfvAIcAKPMzEkOkK7A7Vs19BHsNgmeHnivKC4BGxNIqBbcQFpYfwEllc5/MSte8vV8yblsb9RP7LErNUzuN+mcz4B0K+CilhmUrJ8pM3yjaxXgaXPe4K1aq0DTdT+saLJegiUw+FtRgDjsVv3y76AZQ==
    clientSecret: AgCt2GqJRT+bFb121c7yQLUnzEgBNDDKw14LraKwGtqEz9rYgiAg1oplx0gkxPXbZZmSJvqKI//Z1+I63wuXHUQf6bh+vZGc83BXhlpwXaRZSAIZeZGYN84DhBWAg722doUZpRSoWGpjKs/cDFvS5GXS5gqkkbMTx0CyMqYYguMlm2g5hTjYx0Euz5emj9M45rRN+v6OfQQUCaF8GR8gXD7q3AeSZJ8gcvBtRnrKIO7wR1hR39tLbqd8h7qyF68wQunJGLWH8E3sHLNrFOdDYUj/C5r41Oavv4ZI9Mn2kHGHZ/AkdH6MukXgHTa35DjeGXZYMA9p6ZCmF6rWPH3eAMwClNkllx+NQkFDPRdTcWfY8jS59ZiGOTY+kBcuOy91rMUv3fw5mHAAIgCjeat7id9hynbRwy/DOP8IHE1yYykyxKBi2SRmFey7vdwM7lKU63Xh81FCWxlpVViwYqkt+ITAHPZC2/y6L8wzKlYe1Ksj1wFLpCLyHB0KQPtZjY6MXzMnuqybXuVkgttlug1pc2qX3bbOgnSo5MHas2lKHJrxM6TV5Zo+FLgUMkZ2+2pxQFllteJZjae/gmVAGukPKbIrDcDGaeWDacf7ebn7A1MqKZBf1z/Tmk3+HzTxlnwjmJlKxqaps7l2HLnJN7Vbh+IfJuuyQqVpSKgiExPysI0Hn5SphKKA5bMgHMZFTFyyWT2XQNTpbQoDdjPVWDWLbmArONOX3C/XPf/9h1YlgvAM9XhFyOz7ruDcjzVP28uL07uqSMUJtWj5TU2MfNEtBCU0
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale-operator
