apiVersion: v2
name: hcloud-csi
description: A Helm chart for Hetzner Cloud CSI Driver
type: application
version: 0.1.0

dependencies:
  - name: hcloud-csi
    version: ~2.18
    repository: https://charts.hetzner.cloud
