vpa:
  recommender:
    enabled: true
    replicaCount: 1
    revisionHistoryLimit: 0
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
    podMonitor:
      enabled: false
      annotations: {}
      labels: {}

  updater:
    enabled: true
    replicaCount: 1
    revisionHistoryLimit: 0
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
    podMonitor:
      enabled: false
      annotations: {}
      labels: {}

  admissionController:
    enabled: true
    replicaCount: 1
    revisionHistoryLimit: 0
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
