cert-manager:
  crds:
    enabled: true
    keep: true

  replicaCount: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  prometheus:
    enabled: true

    servicemonitor:
      enabled: false
      prometheusInstance: default
      interval: 60s
      scrapeTimeout: 30s
      labels: {}
      annotations: {}

  webhook:
    replicaCount: 2

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi

    networkPolicy:
      enabled: true

      ingress:
      - from:
        - ipBlock:
            cidr: 0.0.0.0/0

      egress:
      - ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
        - port: 6443
          protocol: TCP
        to:
        - ipBlock:
            cidr: 0.0.0.0/0

  cainjector:
    enabled: true

    replicaCount: 2

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi

  startupapicheck:
    enabled: true

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
