cert-manager:
  crds:
    enabled: true
    keep: true

  replicaCount: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: controller

  prometheus:
    enabled: true

    servicemonitor:
      enabled: false
      prometheusInstance: default
      interval: 60s
      scrapeTimeout: 30s
      labels: {}
      annotations: {}

  webhook:
    replicaCount: 2

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi

    timeoutSeconds: 20

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: cert-manager
          app.kubernetes.io/component: webhook

  cainjector:
    enabled: true

    replicaCount: 2

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: cert-manager
          app.kubernetes.io/component: cainjector

  startupapicheck:
    enabled: true

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
