minecraft:
  # Note: Minecraft is not horizontally scalable.
  # The server state (world data, player data, etc.) cannot be synchronized across multiple replicas,
  # so replicaCount must always be 1 to ensure a consistent game world.
  replicaCount: 1

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 1024Mi

  persistence:
    dataDir:
      enabled: true
      Size: 1Gi
      accessModes:
        - ReadWriteOnce

  minecraftServer:
    eula: "TRUE"
    version: "LATEST" # Automatically downloads and runs the latest stable Minecraft server version.
    type: VANILLA
    serviceType: LoadBalancer # Exposes the server externally.
    loadBalancerClass: tailscale # Uses the "tailscale" load balancer class.
    rcon:
      enabled: true
      withGeneratedPassword: true # Automatically generate a strong random password.
      port: 25575
    whitelist:
      - "bcrisp4"
    ops:
      - "bcrisp4"

  mcbackup:
    enabled: true
    backupInterval: 1h # Take hourly backups.
    pruneBackupsDays: 7 # Prune backups older than 7 days.
    compressMethod: "zstd" # Use zstd compression for best performance.
    zstdParameters: "-3 --long=25 --single-thread" # Tuned zstd parameters.
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi # Enforces a memory limit for mcbackup.
    persistence:
      backupDir:
        enabled: true
        Size: 10Gi # Increased storage to accommodate hourly backups for 7 days.
        accessModes:
          - ReadWriteOnce
