minecraft:
  nameOverride: "1"

  # Note: Minecraft is not horizontally scalable.
  # The server state (world data, player data, etc.) cannot be synchronized across multiple replicas,
  # so replicaCount must always be 1 to ensure a consistent game world.
  replicaCount: 1

  workloadAsStatefulSet: false
  strategyType: RollingUpdate

  resources:
    requests:
      cpu: 1000m
      memory: 1000Mi
    limits:
      memory: 1200Mi

  persistence:
    dataDir:
      enabled: true
      Size: 1Gi
      accessModes:
        - ReadWriteOnce

  minecraftServer:
    eula: "TRUE"
    version: "LATEST" # Automatically downloads and runs the latest stable Minecraft server version.
    type: VANILLA
    serviceType: LoadBalancer # Exposes the server externally.
    loadBalancerClass: tailscale # Uses the "tailscale" load balancer class.
    whitelist: bcrisp4
    ops: bcrisp4
    motd: "Minecraft server numero uno"
    viewDistance: 16
    difficulty: "normal"

    rcon:
      enabled: true
      existingSecret: rcon-secret
      port: 25575

  extraEnv:
    PAUSE_WHEN_EMPTY_SECONDS: -1

  mcbackup:
    enabled: true
    backupInterval: 1h # Take hourly backups.
    pruneBackupsDays: 7 # Prune backups older than 7 days.
    compressMethod: "zstd" # Use zstd compression for best performance.
    zstdParameters: "-3 --long=25 --single-thread" # Tuned zstd parameters.
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi # Enforces a memory limit for mcbackup.
    persistence:
      backupDir:
        enabled: true
        Size: 10Gi # Increased storage to accommodate hourly backups for 7 days.
        accessModes:
          - ReadWriteOnce
